name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo -E apt-get update
        sudo -E apt-get -y install gettext
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run build
      run: ./bin/build
